ConferenceSubmission/Models/SubmissionPayment.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConferenceSubmission.Models
{
    /// <summary>
    /// Represents a payment for a submission.  Some conferences require
    /// non-members to pay to submit.
    /// </summary>
    public class SubmissionPayment
    {
        public SubmissionPayment()
        {
        }

        public int SubmissionPaymentId { get; set; }

        public int SubmissionId { get; set; }

        public Submission Submission { get; set; }

        public int PaymentAmount { get; set; }

        public DateTime PaymentDateTime { get; set; }

        [StringLength(250)]
        public string PaymentTransactionId { get; set; }

    }
}

ConferenceSubmission/ViewModels/SubmissionPaymentViewModel.cs
using System;
namespace ConferenceSubmission.ViewModels
{
    public class SubmissionPaymentViewModel
    {
        public Boolean SuccessfulPayment { get; set; }

        public string PaymentResult { get; set; }

        public string PaymentTransactionId { get; set; }

        public int SubmissionId { get; set; }

        public bool ShowDisclosureLink { get; set; }

        public string DisclosureLinkMethod { get; set; }

    }
}

ConferenceSubmission/Controllers/PaymentController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using ConferenceSubmission.BindingModels;
using Microsoft.AspNetCore.Authorization;
using Serilog;
using ConferenceSubmission.Mappers;
using AuthorizeNet.Api.Contracts.V1;
using AuthorizeNet.Api.Controllers.Bases;
using AuthorizeNet.Api.Controllers;
using ConferenceSubmission.ViewModels;
using Microsoft.Extensions.Configuration;
using ConferenceSubmission.Services;
using ConferenceSubmission.Models;

namespace ConferenceSubmission.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {

        private readonly IUserMapper _userMapper;

        private IConfiguration _configuration;

        private ISubmissionPaymentService _submissionPaymentService;

        private ISubmissionService _submissionService;

        private IDisclosureService _disclosureService;

        private readonly IEmailNotificationService _emailNotificationService;

        public PaymentController(IUserMapper userMapper, IConfiguration configuration, 
                                 ISubmissionPaymentService submissionPaymentService,
                                 ISubmissionService submissionService,
                                 IDisclosureService disclosureService,
                                 IEmailNotificationService emailNotificationService)
        {
            _userMapper = userMapper;

            _configuration = configuration;

            _submissionPaymentService = submissionPaymentService;

            _submissionService = submissionService;

            _disclosureService = disclosureService;

            _emailNotificationService = emailNotificationService;

        }

        /// <summary>
        /// Responds to user's initial http request to pay for submitting.
        /// </summary>
        /// <returns>The index.</returns>
        /// <param name="submissionId">Conference identifier.</param>
        public IActionResult Index(int submissionId) {

            /*
             * NOTE: Since fee to submit is the same for all submission categories
             * that require payment the fee value is stored in the application's
             * configuration
             */
            CreditCardPaymentBindingModel creditCardPaymentBindingModel = new CreditCardPaymentBindingModel
            {

                SubmissionId = submissionId,
                PaymentAmount = Decimal.Parse(_configuration["SubmissionPayment:SubmissionFee"])


            };

            return View(creditCardPaymentBindingModel);


        }

        /// <summary>
        /// Responds to user's http post request to pay for submission.
        /// </summary>
        /// <returns>View for successful payment</returns>
        ///<param name="creditCardPaymentBindingModel">Credit card payment binding model</param>
        public IActionResult SubmissionPayment(CreditCardPaymentBindingModel creditCardPaymentBindingModel)
        {

            if (!ModelState.IsValid)
            {

                return View("Index", creditCardPaymentBindingModel);

            }

            var user = _userMapper.Map(User.Claims);

            Log.Information($"{user.STFMUserId} wants to pay for submission id # {creditCardPaymentBindingModel.SubmissionId}");

            /*
             * If the Production configuration value is false we are using the Authorize.net Test 
             * Sandbox and NOT production Authorize.net - so the credit card will NOT be charged.
             */

            Boolean production = Convert.ToBoolean(_configuration["Authorize.net:Production"]);

            Log.Information($"Application is using Authorize.net setting of production: {production}");

            SubmissionPaymentViewModel submissionPaymentViewModel = 
                _submissionPaymentService.ProcessPaymentNew(_configuration["Authorize.net:APILoginKey"],
                                                         _configuration["Authorize.net:TransactionKey"], 
                                                         production, creditCardPaymentBindingModel);

            if (submissionPaymentViewModel.SuccessfulPayment) {

                /*
                 * We only save successful payments to the database
                 */

                SubmissionPayment submissionPayment = new SubmissionPayment
                {

                    PaymentAmount = (int)creditCardPaymentBindingModel.PaymentAmount,

                    PaymentDateTime = DateTime.Now,

                    PaymentTransactionId = submissionPaymentViewModel.PaymentTransactionId,

                    SubmissionId = creditCardPaymentBindingModel.SubmissionId

                };

                _submissionService.AddSubmissionPayment(submissionPayment);

                submissionPayment.Submission = _submissionService.GetSubmission(submissionPayment.SubmissionId);

                _emailNotificationService.SendSubmissionPaymentEmail(user.Email, submissionPayment);

                Log.Information($"Submission payment email sent to {user.Email}");

            }


            DateTime conferenceStartDate = _submissionService.GetSubmission(creditCardPaymentBindingModel.SubmissionId).Conference.ConferenceStartDate;

            Log.Information("About to check if disclosure is required - conference start date is " + conferenceStartDate + " STFM User id is " + user.STFMUserId);

            if (_disclosureService.GetDisclosure(user.STFMUserId) == null)
            {

                Log.Information("STFM User id " + user.STFMUserId + " does not have a disclosure.  So must complete a new disclosure.");

                submissionPaymentViewModel.ShowDisclosureLink = true;

                submissionPaymentViewModel.DisclosureLinkMethod = "Index";


            } else if (! _disclosureService.isDisclosureCurrent(conferenceStartDate, user.STFMUserId))
            {

                Log.Information("STFM User Id " + user.STFMUserId + " needs to update the disclosure.");

                submissionPaymentViewModel.ShowDisclosureLink = true;

                submissionPaymentViewModel.DisclosureLinkMethod = "EditDisclosure";

            }

            //Redirecting to a new method in order to prevent accidental form resubmission.
            //Passing an anonymous object because the transactionId should not be
            //included in the route values
            return RedirectToAction("SubmissionPaymentProcessed", new
            {
                submissionPaymentViewModel.SuccessfulPayment,
                submissionPaymentViewModel.PaymentResult,
                submissionPaymentViewModel.SubmissionId,
                submissionPaymentViewModel.ShowDisclosureLink,
                submissionPaymentViewModel.DisclosureLinkMethod
            });
        }

        /// <summary>
        /// This method is called internally by the application after it has attempted to process a user's
        /// payment.
        /// </summary>
        /// <param name="submissionPaymentViewModel">A model with results from the payment that was attempted on the user's behalf</param>
        /// <returns>The view that shows the payment results to the user</returns>
        public IActionResult SubmissionPaymentProcessed(SubmissionPaymentViewModel submissionPaymentViewModel)
        {
            var model = new SubmissionPaymentViewModel
            {
                SuccessfulPayment = submissionPaymentViewModel.SuccessfulPayment,
                PaymentResult = submissionPaymentViewModel.PaymentResult,
                SubmissionId = submissionPaymentViewModel.SubmissionId,
                ShowDisclosureLink = submissionPaymentViewModel.ShowDisclosureLink,
                DisclosureLinkMethod = submissionPaymentViewModel.DisclosureLinkMethod
            };
            return View("SubmissionPayment", model);
        }

        /// <summary>
        /// Respond to user's request to view a submission payment.
        /// </summary>
        /// <param name="submissionId"></param>
        /// <returns></returns>
        public IActionResult ViewPayment(int submissionId)
        {

            Submission submission = _submissionService.GetSubmission(submissionId);


            return View("ViewPayment", submission);
        }
    }
}

ConferenceSubmission/Views/Payment/Index.cshtml
@model ConferenceSubmission.BindingModels.CreditCardPaymentBindingModel
@{
    ViewData["Title"] = "Submission Payment";
}


<h1 class="color-primary">Submission Payment</h1>
<hr />
<p>
    Please enter all the information below to pay the $@String.Format("{0:0.00}", Model.PaymentAmount) submission fee.
    If you do not pay the submission fee your submission will not be reviewed. Visa, MasterCard and American Express are accepted.
</p>
<form asp-action="SubmissionPayment" asp-controller="Payment">
    <div class="form-group">
        <label asp-for="BillingFirstName"></label>
        <input class="form-control" asp-for="BillingFirstName" />
        <span asp-validation-for="BillingFirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="BillingLastName"></label>
        <input class="form-control" asp-for="BillingLastName" />
        <span asp-validation-for="BillingLastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="BillingStreet"></label>
        <input class="form-control" asp-for="BillingStreet" />
        <span asp-validation-for="BillingStreet" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="BillingCity"></label>
        <input class="form-control" asp-for="BillingCity" />
        <span asp-validation-for="BillingCity" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="BillingZip"></label>
        <input class="form-control" asp-for="BillingZip" />
        <span asp-validation-for="BillingZip" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CreditCardNumber"></label>
        <input class="form-control" asp-for="CreditCardNumber" />
        <span asp-validation-for="CreditCardNumber" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CreditCardCsvCode"></label>
        <input class="form-control" asp-for="CreditCardCsvCode" />
        <span asp-validation-for="CreditCardCsvCode" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="CreditCardExpirationDate"></label>
        <input class="form-control" asp-for="CreditCardExpirationDate" />
        <span asp-validation-for="CreditCardExpirationDate" class="text-danger"></span>
    </div>

    <input type="hidden" asp-for="SubmissionId" value="@Model.SubmissionId" />
    <input type="hidden" asp-for="PaymentAmount" value="@Model.PaymentAmount" />
    <button type="submit" class="btn btn-primary">Pay For Submission</button> &nbsp;&nbsp;&nbsp;
    <a class="btn btn-default" href="@Url.Action("Index", "Home" )">Cancel</a>
</form>

@section scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }

ConferenceSubmission/Views/Payment/SubmissionPayment.cshtml
@model ConferenceSubmission.ViewModels.SubmissionPaymentViewModel
@{
    ViewData["Title"] = "Submission Payment Processed";
}
<h3>@Model.PaymentResult</h3>
@if (Model.SuccessfulPayment == false)
{

    <p class="text-15">Your payment was not successful.  You can try to pay again after completing the submission process
    and then clicking on view submission.  On that page will be a link you can use to try paying again. </p>

}


@if (Model.ShowDisclosureLink)
{

    <p class="text-15">You need to complete a disclosure.</p>
    <a class="text-15" asp-controller="Disclosure" asp-action="@Model.DisclosureLinkMethod" asp-route-submissionId="@Model.SubmissionId"><i class="fas fa-pen"></i> Complete Disclosure</a>


}
else
{
    <p>
        Click here to <a class="text-16" asp-controller="Submission" asp-action="ProposalSuccess" asp-route-submissionId="@Model.SubmissionId"><i class="fas fa-eye"></i> View Submission</a>
        and read through additional instructions for how to add presenters to your submission.
    </p>
}

ConferenceSubmission/Views/Payment/ViewPayment.cshtml
@model ConferenceSubmission.Models.Submission
@{
    ViewData["Title"] = "Submission Payment Receipt";
}

<h3>Submission Payment Receipt</h3>

<div class="mar-bot-20">
    <p class="cat-name-md">Conference: <span class="cat-info-md">@Html.Raw(Model.Conference.ConferenceLongName)</span></p>

    <partial name="DisplaySubmissionCategory" model="new ConferenceSubmission.ViewModels.DisplaySubmissionCategoryViewModel { SubmittedCategory = Model.SubmissionCategory.SubmissionCategoryName, AcceptedCategory = Model.AcceptedCategory.SubmissionCategoryName }" />

    <p class="cat-name-md">Submission Id: <span class="cat-info-md">@Model.SubmissionId</span></p>

    <p class="cat-name-md">Submission Title: <span class="cat-info-md">@Model.SubmissionTitle</span></p>

</div>
<div class="mar-bot-20">
    <p class="cat-name-md">Payment Details</p>
    <p class="cat-info-md">Amount: $@Model.SubmissionPayment.PaymentAmount <br />
    Payment Date: @Model.SubmissionPayment.PaymentDateTime.ToString("MMMM dd, yyyy") <br />
    Payment Transaction Id: @Model.SubmissionPayment.SubmissionPaymentId </p>

</div>

<div class="col-xl-2 col-lg-2 col-md-3">
    <p class="cat-info-md"><a class="card-link" asp-controller="Submission" asp-action="ViewSubmission" asp-route-submissionId="@Model.SubmissionId"> <i class="fas fa-eye" aria-hidden="true"></i> Return to Submission</a></p>
</div>