ConferenceSubmission/Models/Submission.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ConferenceSubmission.Models
{
    /// <summary>
    /// Represents a submission for presentation at a conference.
    /// </summary>
    [Auditable]
    public class Submission
    {
        public Submission()
        {

            ParticipantLink = new List<SubmissionParticipant>();

        }

        public int SubmissionId { get; set; }

        [StringLength(250)]
        [Required]
        public string SubmissionTitle { get; set; }

        [Required]
        public string SubmissionAbstract { get; set; }

        /// <summary>
        /// Represents the category the submitter entered 
        /// originally for the proposed presentation.
        /// </summary>
        /// <value>The submission category identifier.</value>
        [ForeignKey("SubmissionCategory")]
        public int SubmissionCategoryId { get; set; }

        public SubmissionCategory SubmissionCategory { get; set; }

        /// <summary>
        /// Initially the AcceptedCategoryId will match the
        /// SubmissionCategoryId.  After the submission is
        /// accepted this value may be changed if the submission
        /// will be presented in a category that is different
        /// then the original SubmissionCategoryId.
        /// </summary>
        /// <value>The accepted category identifier.</value>

        [ForeignKey("AcceptedCategory")]
        public int AcceptedCategoryId { get; set; }

        public SubmissionCategory AcceptedCategory { get; set; }

        public DateTime SubmissionCreatedDateTime { get; set; }

        public DateTime SubmissionLastUpdatedDateTime { get; set; }

        [Auditable]
        public int SubmissionStatusId { get; set; }

        public SubmissionStatus SubmissionStatus { get; set; }

        public SubmissionPayment SubmissionPayment { get; set; }

        public ConferenceSession ConferenceSession { get; set; }

        public List<VirtualConferenceSession> VirtualConferenceSessions {get; set;}

        public List<SubmissionParticipant> ParticipantLink { get; set; }

        public List<VirtualMaterial> VirtualMaterials { get; set; }

        [ForeignKey("ConferenceId")]
        public Conference Conference { get; set; }

        /// <summary>
        /// Gets or sets a value indicating whether this
        /// <see cref="T:ConferenceSubmission.ViewModels.SubmissionWithProposalAnswersViewModel"/> submission 
        /// is completed.
        /// A submission is considered completed if user has answered all the category
        /// specific proposal form questions where an answer is required.
        /// </summary>
        /// <value><c>true</c> if submission completed; otherwise, <c>false</c>.</value>
        public bool SubmissionCompleted { get; set; }

        /// <summary>
        /// If true an admin person has edited the accepted submission
        /// for display online and in the brochure.  
        /// </summary>
        public bool SubmissionAdminEdited { get; set; }

        /// <summary>
        /// If true, the participant order has been modified by a submission admin or by a 
        /// submission participant
        /// </summary>
        public bool ParticipantOrderModified { get; set; }

        public List<SubmissionPresentationMethod> SubmissionPresentationMethods {get; set;}

    }
}

ConferenceSubmission/Models/SubmissionAction.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ConferenceSubmission.Models
{
    public enum SubmissionAction
    {
        VIEW,
        EDIT,
        WITHDRAW,
        UPDATE_PARTICIPANTS,
        UPLOAD_MATERIAL,
        ACCEPT_OR_DECLINE_PRESENTATION_METHOD,
        WITHDRAW_VIRTUAL_PRESENTATION
    }
}

ConferenceSubmission/ViewModels/SubmissionPrintViewModel.cs
using ConferenceSubmission.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace ConferenceSubmission.ViewModels
{
    public class SubmissionPrintViewModel
    {
        public string                       ConferenceName          { get; set; }
        public int                          SubmissionId            { get; set; }
        public string                       SubmissionTitle         { get; set; }
        public string                       AcceptedCategory        { get; set; }
        public string                       SubmissionCategory      { get; set; }
        public string                       SubmissionAbstract      { get; set; }
        public List<SubmissionFormField>    SubmissionFormFields    { get; set; }
        public List<Presenter>              Presenters              { get; set; }
        public string                       ImagePath               { get; set; }

        public string sessionCode { get; set; }

        public DateTime sessionStartDatetime { get; set; }

        public DateTime sessionEndDatetime { get; set; }

        public string sessionLocation { get; set; }

        public string sessionTrack { get; set; }


        //Public helper methods
        public string GetFileName()
        {
            //Regex that matches characters that are invalid in windows file names
            var illegalInFileName = new Regex(@"[\\/:*?""<>|]");
            return $"{illegalInFileName.Replace(SubmissionTitle.Substring(0, Math.Min(50, SubmissionTitle.Length)), "").Replace(' ', '_')}.pdf";
        }
    }
}

ConferenceSubmission/ViewModels/SubmissionProposalInputViewModel.cs
using System;
namespace ConferenceSubmission.ViewModels
{
    /// <summary>
    /// Submission proposal input view model.
    /// </summary>
    public class SubmissionProposalInputViewModel
    {

        public int SubmissionId { get; set; }

        public int SubmissionCategoryId { get; set; }

        public string SubmissionTitle { get; set; }

        public string ConferenceName { get; set; }

        public string SubmissionCategoryName { get; set; }

        public string SubmissionAbstract { get; set; }

    }
}

ConferenceSubmission/Controllers/SubmissionController.cs
using System;
using System.Collections.Generic;
using ConferenceSubmission.Services;
using ConferenceSubmission.ViewModels;
using ConferenceSubmission.BindingModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Serilog;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Linq;
using ConferenceSubmission.Mappers;
using ConferenceSubmission.Models;
using Microsoft.AspNetCore.Http;
using System.Security.Cryptography;
using Microsoft.AspNetCore.Cryptography.KeyDerivation;
using System.Text;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System.Globalization;
using Microsoft.Extensions.Logging;
using System.Threading.Tasks;
using Dropbox.Api;
using Dropbox.Api.Files;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;

namespace ConferenceSubmission.Controllers
{
    /// <summary>
    /// Responds to user requests related to creating or editing a submission.
    /// </summary>
   [Authorize]
    public class SubmissionController : Controller
    {

        private readonly ISubmissionCategoryService _SubmissionCategoryService;

        private readonly ISubmissionService _submissionService;

        private readonly IParticipantService _participantService;

        private readonly IConferenceService _conferenceService;

        private readonly ISubmissionStatusService _submissionStatusService;

        private readonly IFormFieldService _formFieldService;

        private readonly IEncryptionService _encryptionService;

        private readonly IUserMapper _userMapper;

        private readonly ISubmissionParticipantService _submissionParticipantService;

        private IConfiguration _configuration;

        private readonly IDisclosureService _disclosureService;

        private readonly IHostingEnvironment _hostingEnvironment;

        private readonly ISubmissionPrintService _submissionPrintService;

        private readonly IEmailNotificationService _emailNotificationService;

        private readonly ISalesforceAPIService _salesforceAPIService;

        private readonly IVirtualMaterialService _virtualMaterialService;

        private readonly IVirtualConferenenceDataService _virtualConferenenceDataService;

        public SubmissionController(ISubmissionCategoryService submmissionCategoryService,
                                    ISubmissionService submissionService,
                                    IParticipantService participantService,
                                    IConferenceService conferenceService,
                                    ISubmissionStatusService submissionStatusService,
                                    IFormFieldService formFieldService,
                                    IEncryptionService encryptionService,
                                    IUserMapper userMapper,
                                    ISubmissionParticipantService submissionParticipantService,
                                    IConfiguration configuration,
                                    IDisclosureService disclosureService,
                                    IHostingEnvironment hostingEnvironment,
                                    ISubmissionPrintService submissionPrintService,
                                    IEmailNotificationService emailNotificationService,
                                    ISalesforceAPIService salesforceAPIService,
                                    IVirtualMaterialService virtualMaterialService,
                                    IVirtualConferenenceDataService virtualConferenenceDataService
                                   )
        {

            _SubmissionCategoryService = submmissionCategoryService;

            _submissionService = submissionService;

            _participantService = participantService;

            _conferenceService = conferenceService;

            _submissionStatusService = submissionStatusService;

            _formFieldService = formFieldService;

            _encryptionService = encryptionService;

            _userMapper = userMapper;

            _submissionParticipantService = submissionParticipantService;

            _configuration = configuration;

            _disclosureService = disclosureService;

            _hostingEnvironment = hostingEnvironment;

            _submissionPrintService = submissionPrintService;

            _emailNotificationService = emailNotificationService;

            _salesforceAPIService = salesforceAPIService;

            _virtualMaterialService = virtualMaterialService;

            _virtualConferenenceDataService = virtualConferenenceDataService;
        }

        /// <summary>
        /// Responds to user's initial http request to select the submission
        /// category.  User is directed here after selecting the conference
        /// on the submission home page.
        /// </summary>
        /// <returns>The Submission/Index view page.</returns>
        /// <param name="conferenceId">Conference identifier for the conference user is submitting to.</param>
        public IActionResult Index(int conferenceId)
        {

            Conference conference = _conferenceService.GetConference(conferenceId);

            var user = _userMapper.Map(User.Claims);

            bool isAdminUser = _salesforceAPIService.isAdminUser(User.Claims);

            //Business rule do not let normal users submit if CFP deadline has past
            //Check if conference CFP deadline has passed and if user is not an admin then return user to home page

            Log.Information($"User wants to create a new submission proposal for conferenceId {conferenceId} at {DateTime.UtcNow.AddHours(-6)} and CFP Deadline is {conference.ConferenceCFPEndDate}");

            if (conference.ConferenceCFPEndDate.CompareTo(DateTime.UtcNow.AddHours(-6)) < 0 && ! isAdminUser)
            {
                return RedirectToAction(actionName: "Index", controllerName: "Home");
            }

            SubmissionCategoryBindingModel submissionCategoryBindingModel = new SubmissionCategoryBindingModel
            {
                ConferenceId = conferenceId,

                ConferenceName = conference.ConferenceLongName,

                SubmissionCategoryItems = GetSubmissionCategoryItems(conferenceId),

                SubmissionPaymentRequirementText = conference.SubmissionPaymentRequirementText,

                CategoryDetailUrl = conference.CategoryDetailUrl

            };

            

            /*
             * If the there are submission categories that require payment and the
             * user membership status means this user must pay to submit to those
             * submission categories we need to notify user on the view page
             */
            submissionCategoryBindingModel.DisplaySubmissionRequirementText =
                _submissionService.DisplayPaymentRequirementText(submissionCategoryBindingModel.SubmissionCategoryItems, user.STFMUserId);

            return View(submissionCategoryBindingModel);

        }

        /// <summary>
        /// Responds to user's initial http request to select the submission
        /// category for a CERA submission.  User is directed here after selecting the conference
        /// on the CERA submission home page.
        /// </summary>
        /// <returns>The Submission/StartCera view page.</returns>
        /// <param name="conferenceId">Conference identifier for the conference user is submitting to.</param>
        public IActionResult StartCera(int conferenceId)
        {
            Conference conference = _conferenceService.GetConference(conferenceId);

            SubmissionCategoryBindingModel submissionCategoryBindingModel = new SubmissionCategoryBindingModel
            {
                ConferenceId = conferenceId,

                ConferenceName = conference.ConferenceLongName,

                SubmissionCategoryItems = GetSubmissionCategoryItems(conferenceId),

                SubmissionPaymentRequirementText = conference.SubmissionPaymentRequirementText,

                CategoryDetailUrl = conference.CategoryDetailUrl

            };

            var user = _userMapper.Map(User.Claims);

            /*
             * If the there are submission categories that require payment and the
             * user membership status means this user must pay to submit to those
             * submission categories we need to notify user on the view page
             */
            submissionCategoryBindingModel.DisplaySubmissionRequirementText =
                _submissionService.DisplayPaymentRequirementText(submissionCategoryBindingModel.SubmissionCategoryItems, user.STFMUserId);

            return View(submissionCategoryBindingModel);

        }

        /// <summary>
        /// Responds to user's initial http request to create a new submission after
        /// user has previously selected the conference and then the submission category.
        /// </summary>
        /// <returns>The Submission/StartSubmission view page.</returns>
        /// <param name="conferenceId">Conference identifier for the conference user is submitting to.</param>
        public IActionResult StartSubmission(int conferenceId, int selectedSubmissionCategory)
        {
            Log.Information($"User wants to create a new submission proposal for conferenceId {conferenceId} and categoryId {selectedSubmissionCategory}");

            Conference conference = _conferenceService.GetConference(conferenceId);

            SubmissionCategory submissionCategory = _SubmissionCategoryService.GetSubmissionCategory(selectedSubmissionCategory);

            BaseSubmissionBindingModel baseSubmissionBindingModel = new BaseSubmissionBindingModel
            {
                ConferenceId = conferenceId,

                ConferenceName = conference.ConferenceLongName,

                SelectedSubmissionCategory = selectedSubmissionCategory,

ConferenceSubmission/Views/Submission/AlreadyUploaded.cshtml
@model ConferenceSubmission.ViewModels.SubmissionWithProposalAnswersViewModel

@{
    ViewData["Title"] = $"Submission: {Model.SubmissionId}";
}

<h3 style="color:red">Our records show that a poster has previously been provided for this submission.  See details below.</h3>
<h4 class="text-primary">Submission Details</h4>
<hr />
<div class="mar-bot-20">

    <p class="cat-name-md">Submission Id: <span class="cat-info-md">@Model.SubmissionId</span></p>

    <p class="cat-name-md">Submission Title: <span class="cat-info-md">@Model.SubmissionTitle</span></p>

    @if (Model.VirtualMaterials.Count > 0)
    {
        <li class="list-group-item">
            <p class="cat-name-md">Uploaded Files:</p>
            @foreach (var file in Model.VirtualMaterials)
            {
        <p class="cat-name-md mar-left-10">
            <span class="badge badge-primary pad-5 text-12">@file.MaterialType</span>
            @if (file.MaterialType.ToLower() == "link")
            {
                <span class="cat-info-md"><a target="_blank" href="@file.MaterialValue">@file.MaterialValue</a></span>
            }
            else
            {
                <span class="cat-info-md">@file.MaterialValue</span>
            }

            - Uploaded on @file.UploadedDateTime.ToString("MM/dd/yyyy") at @file.UploadedDateTime.ToString("HH:mm")
        </p>
            }
        </li>
    }

    <p>If you want to remove all uploaded material for this submission and start over click on 
    <a class="btn btn-primary" asp-controller="Submission" asp-action="RemoveUploadedMaterial" asp-route-submissionId="@Model.SubmissionId"><i class="far fa-plus-square mar-right-3"></i> Remove Uploaded Material</a>. <br />
    <b>IMPORTANT: Removing these uploaded file(s) 
    cannot be undone. You will need to upload new files for presentation.</b></p>

    <p>If you have questions please email us at <a href="mailto:stfmoffice@stfm.org">stfmoffice@stfm.org</a></p>
</div>

ConferenceSubmission/Views/Submission/CeraProposalSuccess.cshtml
@model ConferenceSubmission.ViewModels.SubmissionWithProposalAnswersViewModel
@using ConferenceSubmission.Extensions
@{
    ViewData["Title"] = "CERA Survey Proposal";
}
<h1 class="text-primary">Submission Details</h1>
<hr />
<div class="alert alert-primary help-text" role="alert">
    <p class="mar-bot-0">Your CERA survey proposal has been successfully submitted.</p>
    <a href="/Cera" class="card-link">Return to the CERA dashboard</a>
</div>
<div class="mar-bot-20">
    <p class="cat-name-md">CERA Survey: <span class="cat-info-md">@Html.Raw(Model.ConferenceName)</span></p>
    <p class="cat-name-md">Category: <span class="cat-info-md">@Model.SubmissionCategoryName</span></p>
    <p class="cat-name-md">Submission Id: <span class="cat-info-md">@Model.SubmissionId</span></p>
    <p class="cat-name-md">Submission Title: <span class="cat-info-md">@Model.SubmissionTitle</span></p>
    <p class="cat-name-md">
        Submission Completed: <span class="cat-info @(Model.SubmissionCompleted ? "text-green" : "text-red")">@Model.SubmissionCompleted</span>
    </p>
    <p class="cat-name-md">
        <a class="card-link" asp-controller="Submission" asp-action="EditProposalAnswers" asp-route-submissionId="@Model.SubmissionId"><i class="fas fa-pen" aria-hidden="true"></i> Edit Submission</a>
    </p>
</div>

@if (Model.SubmissionFormFields.Count > 0)
{
    <div class="mar-bot-20">
        <h3 class="mar-bot-5">Submission Proposal Questions</h3>
        <hr class="hr-sm" />
        @foreach (var submissionFormField in Model.SubmissionFormFields.OrderBy(s => s.FormField.FormFieldSortOrder))
        {
            string question = submissionFormField.FormField.GetPropertyValue("label");
            if (!question.Equals(""))
            {
                <div class="mar-bot-25">
                    <p class="cat-name-sm mar-bot-1">Question: <span class="cat-info-sm">@question</span></p>
                    @if (submissionFormField.FormField.FormFieldType.ToLower() == "textarea")
                    {
                        <p class="cat-name-sm">Response:</p>
                        <p class="cat-info-sm">@Html.Raw(submissionFormField.SubmissionFormFieldValue.ReplaceLineBreaksWithBreakTags())</p>
                    }
                    else
                    {
                        <p class="cat-name-sm">Response: <span class="cat-info-sm">@submissionFormField.SubmissionFormFieldValue</span></p>
                    }
                </div>
            }
        }
    </div>
}

ConferenceSubmission/Views/Submission/PaymentRequired.cshtml
@model ConferenceSubmission.ViewModels.SubmissionWithProposalAnswersViewModel
@{
    ViewData["Title"] = "Submission Payment Required";
}
<h1>Submission Payment Required</h1>
<p>There is a fee of $@Model.SubmissionFee to submit this submission.</p>
<p><a asp-controller="Payment" asp-action="Index" asp-route-submissionId="@Model.SubmissionId">Click here to pay</a> for submitting this submission.  If you do not complete the payment successfully 
your submission will not be reviewed.</p>

ConferenceSubmission/Views/Submission/ProposalSuccess.cshtml
@model ConferenceSubmission.ViewModels.SubmissionWithProposalAnswersViewModel
@using ConferenceSubmission.Extensions
@{
    ViewData["Title"] = "Submission Proposal";
}
<h1 class="text-primary">Submission Details</h1>
<hr />
<div class="alert alert-primary help-text" role="alert">
    <p class="mar-bot-0">Your submission has been successfully submitted. To <strong>add presenters</strong> follow the instructions listed below under "Invite Presenter(s) to Submission".</p>
    <a href="/" class="card-link">Return to the main dashboard</a>
</div>
<div class="mar-bot-20">
    <p class="cat-name-md">Conference: <span class="cat-info-md">@Html.Raw(Model.ConferenceName)</span></p>
    <p class="cat-name-md">Category: <span class="cat-info-md">@Model.SubmissionCategoryName</span></p>
    <p class="cat-name-md">Submission Id: <span class="cat-info-md">@Model.SubmissionId</span></p>
    <p class="cat-name-md">Submission Title: <span class="cat-info-md">@Model.SubmissionTitle</span></p>
    <p class="cat-name-md">
        Submission Completed: <span class="cat-info @(Model.SubmissionCompleted ? "text-green" : "text-red")">@Model.SubmissionCompleted</span>
    </p>
    <p class="cat-name-md">
        <a class="card-link" asp-controller="Submission" asp-action="EditSubmissionBaseDetails" asp-route-submissionId="@Model.SubmissionId"><i class="fas fa-pen" aria-hidden="true"></i> Edit Submission</a>
    </p>
</div>
<div class="mar-bot-25">
    <h3 class="mar-bot-5">Invite Presenter(s) to Submission</h3>
    <hr class="hr-sm" />

    <partial name="ExampleAddParticipantEmail" model="new ConferenceSubmission.ViewModels.ExampleAddParticipantEmailViewModel { AddParticipantUrl = Model.AddParticipantUrl, ConferenceName = Model.ConferenceName, SubmissionTitle = Model.SubmissionTitle }" />


    <!-- The following commented out code displays a clickable icon that allows the user to copy the AddParticipantUrl to the clipboard.
     Leaving this code in because we may want to use it at some point. -->
    @*<p class="cat-info-md">
            <button type="button"
                    data-toggle="tooltip"
                    data-placement="top"
                    title="Copy link to clipboard"
                    class="mar-right-10 btn btn-outline-primary btn-lg"
                    onclick="copyToClipboard('@Model.AddParticipantUrl')">
                <i class="far fa-copy"></i>
            </button> @Model.AddParticipantUrl
        </p>*@
</div>
<div class="mar-bot-20">
    <h3 class="mar-bot-5">Submission Abstract</h3>
    <hr class="hr-sm" />
    <p class="text-14">@Html.Raw(Model.SubmissionAbstract.ReplaceLineBreaksWithBreakTags())</p>
</div>
@if (Model.SubmissionFormFields.Count > 0)
{
    <div class="mar-bot-20">
        <h3 class="mar-bot-5">Submission Proposal Questions</h3>
        <hr class="hr-sm" />
        @foreach (var submissionFormField in Model.SubmissionFormFields.OrderBy(s => s.FormField.FormFieldSortOrder))
        {
            string question = submissionFormField.FormField.GetPropertyValue("label");
            if (!question.Equals(""))
            {
                <div class="mar-bot-25">
                    <p class="cat-name-sm mar-bot-1">Question: <span class="cat-info-sm">@question</span></p>
                    @if (submissionFormField.FormField.FormFieldType.ToLower() == "textarea")
                    {
                        <p class="cat-name-sm">Response:</p>
                        <p class="cat-info-sm">@Html.Raw(submissionFormField.SubmissionFormFieldValue.ReplaceLineBreaksWithBreakTags())</p>
                    }
                    else
                    {
                        <p class="cat-name-sm">Response: <span class="cat-info-sm">@submissionFormField.SubmissionFormFieldValue</span></p>
                    }
                </div>
            }
        }
    </div>
}

@if (Model.SubmissionPaymentRequirement != SubmissionPaymentRequirement.NONE)
{
    <div class="mar-bot-20">
        <h3 class="mar-bot-5">Submission Payment</h3>
        <hr class="hr-sm" />
        <p class="cat-name-sm mar-bot-1">Submission Fee: <span class="cat-info-sm color-green">$@Model.SubmissionFee</span></p>
        @if (Model.SubmissionPaymentAmountPaid != Model.SubmissionFee)
        {
            <p class="cat-name-sm mar-bot-1">Amount due: <span class="cat-info-sm color-green">$@Model.SubmissionFee</span></p>
            <a asp-controller="Payment" asp-action="Index" asp-route-submissionId="@Model.SubmissionId" class="text-16"><i class="far fa-credit-card"></i> Make Payment</a>
        }
        else
        {
            <p class="cat-name-sm mar-bot-1">Amount paid: <span class="cat-info-sm color-green">$@Model.SubmissionPaymentAmountPaid</span></p>
        }
    </div>
}

<div class="mar-bot-20">
    <h3>Disclosure</h3>
    <hr class="hr-sm" />
    <div class="col-xl-4 col-lg-5 col-md-6 col-sm-12 pad-left-1">

        <partial name="DisplayDisclosureStatus" model="new ConferenceSubmission.ViewModels.DisplayDisclosureStatusViewModel { IsDisclosureCurrent = Model.isDisclosureCurrent }" />

    </div>
</div>

ConferenceSubmission/Views/Submission/ProvideRecordedOnDemandPresentation.cshtml
@model ConferenceSubmission.BindingModels.ProvideRecordedOnDemandPresentationBindingModel

<h2 class="color-primary">@Model.ConferenceName Virtual Conference Supplement Online Presentation</h2>
<hr />
<p>Your submission [@Model.SubmissionId] is eligilble to be included in the @Model.ConferenceName Virtual Conference Supplement. 
    If you would like your Submission to be included in the Virtual Conference Supplement, you will need to 
    provide STFM with a recorded version of your presentation.</p>

<p>
    An FAQ about the Virtual Conference Supplement is available on the STFM website at <a href="@Model.VirtualConferenceFAQ" target="_blank">@Model.VirtualConferenceFAQ</a> -
    if you have questions please email stfmoffice@stfm.org.</p>

<p>Instructions for how to prepare your presentation for the Virtual Conference Supplement were provided in your accept email.</p>

<p>If you agree to prepare your presentation for the Virtual Conference Supplement then you must provide your Virtual Conference Supplement presentation to STFM by 
    @Model.Deadline.
</p>

<div class="mar-top-20">
    <form asp-action="ProvideRecordedOnDemandPresentation" asp-controller="Submission">
        <input class="form-control" asp-for="@Model.SubmissionId" type="hidden" />
        <div class="form-group">
            <select class="form-control" name="WillProvideRecordedOnDemandPresentation">
                <option value="true">Yes, I will provide STFM with a recorded version of my presentation for the virtual conference supplement.</option>
                <option value="false">No, I do not want my submission included in the virtual conference supplement.</option>
            </select>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button> &nbsp;&nbsp;&nbsp;
            <a class="btn btn-default" href="@Url.Action("Index", "Home" )">Cancel</a>
        </div>
    </form>
</div>

@section scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ConferenceSubmission/Views/Submission/StartCera.cshtml
@model ConferenceSubmission.BindingModels.SubmissionCategoryBindingModel
@{
    ViewData["Title"] = "Select CERA Survey";
}
<h1 class="text-primary">Select CERA Survey</h1>
<hr />
<div class="mar-bot-15">
      <p>Learn more about the CERA Surveys here: <a href="@Model.CategoryDetailUrl" target="_blank">@Model.CategoryDetailUrl</a></p>
</div>
@if (Model.DisplaySubmissionRequirementText)
{
    <div class="alert alert-primary help-text" role="alert">
        @Model.SubmissionPaymentRequirementText
    </div>

}

<form asp-action="StartCeraSubmission" asp-controller="Submission">
    <div class="form-group">
        <label asp-for="SelectedSubmissionCategory"></label>
        <select asp-for="SelectedSubmissionCategory" asp-items="@Model.SubmissionCategoryItems" class="form-control">
            <option value="">- Select -</option>
        </select>
        <span asp-validation-for="SelectedSubmissionCategory" class="text-danger"></span>
    </div>

    <input type="hidden" asp-for="ConferenceId" value="@Model.ConferenceId" />
    <button type="submit" class="btn btn-primary">Save and Continue</button> &nbsp;&nbsp;&nbsp;
    <a class="btn btn-default" href="@Url.Action("Index", "Cera")">Cancel</a>

</form>
@section scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        $("#SubmissionTitle").characterCounter({
            limit: '125',
            counterFormat: 'Chars Remaining %1'
        });

        $("#SubmissionAbstract").characterCounter({
            limit: '2500',
            counterFormat: 'Chars Remaining %1'
        });</script>
}

ConferenceSubmission/Views/Submission/UploadMaterial.cshtml
<h2 class="color-primary">Upload Presentation Material</h2>
<hr />

<p class="font-size-1rem">In early 2023, you will receive instructions via email for how to upload your recorded presentation material.</p>