ConferenceSubmission/Models/SubmissionStatus.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace ConferenceSubmission.Models
{
    /// <summary>
    /// Represents the status of a submission (e.g. accepted, declined, 
    /// canceled, withdrawn).
    /// </summary>
    public class SubmissionStatus
    {
        public SubmissionStatus()
        {
        }

        public int SubmissionStatusId { get; set; }

        [StringLength(250)]
        [Required]
        public SubmissionStatusType SubmissionStatusName { get; set; }



        public List<Submission> Submissions { get; set; }
    }
}

ConferenceSubmission/Models/SubmissionStatusType.cs
using System.ComponentModel;

namespace ConferenceSubmission.Models
{
    /// <summary>
    /// Models a submission status type.
    /// </summary>
    public enum SubmissionStatusType
    {
        [Description("Open")]
        OPEN,

        [Description("Pending Review")]
        PENDING_REVIEW,

        [Description("Accepted")]
        ACCEPTED,

        [Description("Not Accepted")]
        DECLINED,

        [Description("Withdrawn")]
        WITHDRAWN,

        [Description("Canceled")]
        CANCELED,

        [Description("Will Present In August")]
        WILL_PRESENT_IN_AUGUST,

        [Description("Pending")]
        PENDING,

        [Description("Will Present At Virtual Conference")]
        WILL_PRESENT_AT_VIRTUAL_CONFERENCE

    }


}

ConferenceSubmission/Controllers/SubmissionStatusController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using ConferenceSubmission.Services;
using ConferenceSubmission.ViewModels;
using ConferenceSubmission.Models;
using System.Collections.Generic;
using Microsoft.AspNetCore.Authorization;
using ConferenceSubmission.Mappers;
using Serilog;
using Dropbox.Api.Files;
using Dropbox.Api;
using System.Threading.Tasks;
using System.Linq;
using System.Globalization;
using Azure.Storage.Blobs;
using Microsoft.Extensions.Configuration;

namespace ConferenceSubmission.Controllers
{

    public class SubmissionStatusController : Controller
    {

        private readonly IConferenceService _conferenceService;

        private readonly ISubmissionService _submissionService;

        private readonly ISubmissionParticipantService _submissionParticipantService;

        private readonly ISalesforceAPIService _salesforceAPIService;

        private readonly IEmailNotificationService _emailNotificationService;

        private readonly ISubmissionStatusService _submissionStatusService;

        private readonly IUserMapper _userMapper;

        private readonly IConferenceSessionService _conferenceSessionService;

        private readonly IVirtualMaterialService _virtualMaterialService;

        private readonly IVirtualConferenenceDataService _virtualConferenenceDataService;

        private readonly IDisclosureService _disclosureService;

        private readonly IConfiguration _configuration;

        public SubmissionStatusController(IConferenceService conferenceService,
                               ISubmissionService submissionService,
            ISubmissionParticipantService submissionParticipantService,
                               ISalesforceAPIService salesforceAPIService,
            IEmailNotificationService emailNotificationService,
            ISubmissionStatusService submissionStatusService,
            IUserMapper userMapper, IConferenceSessionService conferenceSessionService,
            IVirtualMaterialService virtualMaterialService,
            IVirtualConferenenceDataService virtualConferenenceDataService, IDisclosureService disclosureService,
            IConfiguration configuration)
        {

            _conferenceService = conferenceService;

            _submissionService = submissionService;

            _submissionParticipantService = submissionParticipantService;

            _salesforceAPIService = salesforceAPIService;

            _emailNotificationService = emailNotificationService;

            _submissionStatusService = submissionStatusService;

            _userMapper = userMapper;

            _conferenceSessionService = conferenceSessionService;

            _virtualMaterialService = virtualMaterialService;

            _virtualConferenenceDataService = virtualConferenenceDataService;

            _disclosureService = disclosureService;

            _configuration = configuration;
        }



        /// <summary>
        /// For the provided submission id update its submission status to the value provided.
        /// This is used to process submissions for accept and decline.
        /// It is normally called by class ProcessFromFile in project processsubmissions
        /// </summary>
        /// <param name="submissionId">Submission Id</param>
        /// <param name="submissionStatusId">Submission Status Id</param>
        /// <returns></returns>
        public IActionResult UpdateSubmissionStatusAndEmailPresenters(int submissionId, int submissionStatusId)
        {

            //Update the submission status
            _submissionService.UpdateSubmissionStatus(submissionId, submissionStatusId);

            //Get the complete details - use a fake STFM User ID value as it is not needed for our purposes
            var submissionWithProposalAnswersViewModel = _submissionService.GetSubmissionWithProposal(submissionId, "1234567");

            _submissionService.AddSubmissionPresentationsToSubmission(submissionId);

            List<SubmissionParticipant> participants = _submissionParticipantService.GetSubmissionParticipants(submissionId);

            List<string> emailAddresses = new List<string>();

            foreach (SubmissionParticipant participant in participants)
            {
                User user = _salesforceAPIService.GetUserInfo(participant.Participant.StfmUserId).Result;

                string emailAddress = user.Email;

                emailAddresses.Add(emailAddress);


            }

            _emailNotificationService.SendSubmissionAcceptedOrRejectedEmail(submissionWithProposalAnswersViewModel, submissionStatusId, emailAddresses);

            return View();


        }

        /// <summary>
        /// Email lead presenter and submitter for the provided submission ID an email about online presentation.
        /// The value of presentationStatusId will determine which email text to send.  A value of 2 
        /// means we need to know if the presenter will do a recorded online presentation and a value of 3 means 
        /// we need the presenter to provide their material for the online presentation.
        /// </summary>
        /// <param name="submissionId"></param>
        /// <param name="presentationstatusid"></param>
        /// <returns></returns>
        public IActionResult EmailPresentersAboutOnlinePresentation(int submissionId, int presentationStatusId)
        {
            //Get the complete details - use a fake STFM User ID value as it is not needed for our purposes
            var submissionWithProposalAnswersViewModel = _submissionService.GetSubmissionWithProposal(submissionId, "1234567");

            List<SubmissionParticipant> participants = _submissionParticipantService.GetSubmissionParticipants(submissionId);

            List<string> emailAddresses = new List<string>();

            foreach (SubmissionParticipant participant in participants)
            {
                foreach (SubmissionParticipantToParticipantRole submissionParticipantToParticipantRole in participant.SubmissionParticipantToParticipantRolesLink)
                {

                    if (submissionParticipantToParticipantRole.ParticipantRole.ParticipantRoleName == ParticipantRoleType.SUBMITTER ||
                        submissionParticipantToParticipantRole.ParticipantRole.ParticipantRoleName == ParticipantRoleType.LEAD_PRESENTER)
                    {

                        User user = _salesforceAPIService.GetUserInfo(participant.Participant.StfmUserId).Result;

                        string emailAddress = "bruceaphillips@gmail.com";

                        if (user != null)
                        {
                            emailAddress = user.Email;
                        }

                        emailAddresses.Add(emailAddress);
                    }
                }


            }

            _emailNotificationService.SendEmailOnlinePresentation(submissionWithProposalAnswersViewModel, presentationStatusId, emailAddresses);


            return View();
        }


        public IActionResult UpdateSessionWithRoom(int submissionId, string room, string track)
        {
            _conferenceSessionService.UpdateConferenceSessionWithRoom(submissionId, room, track);

            return View();
        }


        /// <summary>
        /// Responds to request to email submitter and main presenter
        /// to provide him/her instructions on how to tell STFM if they 
        /// will present their submissions in at the virutal conference 
        /// or will withdraw.
        /// </summary>
        /// <param name="emailAddress">Email address of person</param>
        /// <param name="conferenceId">Conference Id </param>
        /// <returns></returns>
        public IActionResult EmailPresenterVirtualConference(string emailAddress, int submissionId)
        {
            //Get the complete details - use a fake STFM User ID value as it is not needed for our purposes
            var submissionWithProposalAnswersViewModel = _submissionService.GetSubmissionWithProposal(submissionId, "1234567");
            _emailNotificationService.SendInitialVirtualConferenceEmail(emailAddress, submissionWithProposalAnswersViewModel);

            return View();


        }

        /// <summary>
        /// Responds to request to email submitter and main presenter
        /// to provide him/her instructions on how to upload material
        /// for virtual presentation.
        /// </summary>
        /// <param name="emailAddress">Email address of person</param>
        /// <param name="submissionId">Submission Id </param>
        /// <returns></returns>
        public IActionResult EmailPresenterUploadMaterial(string emailAddress, int submissionId)
        {

            Submission submission = _submissionService.GetSubmission(submissionId);
            _emailNotificationService.SendEmailPresenterUploadMaterial(emailAddress, submission);

            return View();


        }

        /// <summary>
        /// Responds to request to send reminder email to AN2020 
        /// submitter or main presenter
        /// to provide him/her instructions on how to tell STFM if they 
        /// will present their submissions in August or will withdraw.
        /// </summary>
        /// <param name="stfmUserId"></param>
        /// <returns></returns>
        public IActionResult AN2020RemindPresenter(string stfmUserId)
        {
            User user = _salesforceAPIService.GetUserInfo(stfmUserId).Result;

            String emailAddress = user.Email;

            _emailNotificationService.SendAN2020ReminderEmail(emailAddress);

            return View();


        }

        public IActionResult SendCPQIDisclosureReminder(string stfmUserId, int submissionId)
        {
            User user = _salesforceAPIService.GetUserInfo(stfmUserId).Result;

            String emailAddress = user.Email;

            List<SubmissionFormField> submissionFormFields = _submissionService.GetSubmissionFormFields(submissionId).ToList();

ConferenceSubmission/Views/SubmissionStatus/AN2020RemindPresenter.cshtml
@{
    ViewData["Title"] = "Email Sent To AN 2020 Submitter/Main Presenter";
}
    <h1 class="text-primary">Email Sent To AN 2020 Submitter/Main Presenter</h1>

ConferenceSubmission/Views/SubmissionStatus/AddSubmissionPresentationMethods.cshtml
@model ConferenceSubmission.Models.Conference

@{
    ViewData["Title"] = "Submission Presentation Methods Added To Accepted Submissions";
}
<h1 class="text-primary">Submission Presentation Methods Added To Accepted Submissions</h1>

<p>Submission Presentation Methods added to accepted submissions for @Model.ConferenceShortName </p>

ConferenceSubmission/Views/SubmissionStatus/EmailIncompleteReminder.cshtml
@{
    ViewData["Title"] = "Reminder Email For Incomplete Submission Sent to Submitter/Main Presenter";
}
<h1 class="text-primary">Reminder Email For Incomplete Submission Sent to Submitter/Main Presenter</h1>

ConferenceSubmission/Views/SubmissionStatus/EmailPresenterUploadMaterial.cshtml
@{
    ViewData["Title"] = "Initial Email About Uploading Material Sent to Submitter/Main Presenter";
}
    <h1 class="text-primary">Initial Email About Uploading Material Sent to Submitter/Main Presenter</h1>

ConferenceSubmission/Views/SubmissionStatus/EmailPresenterVirtualConference.cshtml
@{
    ViewData["Title"] = "Initial Email About Virtual Conference Sent to Submitter/Main Presenter";
}
    <h1 class="text-primary">Initial Email About Virtual Conference Sent to Submitter/Main Presenter</h1>

ConferenceSubmission/Views/SubmissionStatus/EmailPresentersAboutOnlinePresentation.cshtml
@{
    ViewData["Title"] = "Email Sent For Online Presentation";
}


<p>Email Sent For Online Presentation</p>

ConferenceSubmission/Views/SubmissionStatus/EmailWillPresentReminder.cshtml
@{
    ViewData["Title"] = "Reminder Email For Pending Submission Sent to Submitter/Main Presenter";
}
<h1 class="text-primary">Reminder Email For Pending Submission Sent to Submitter/Main Presenter</h1>

ConferenceSubmission/Views/SubmissionStatus/GetAcceptedEmail.cshtml
@model Submission
@{
    ViewData["Title"] = "Get Accepted Email";
}
<h1 class="text-primary">Get Accepted Email</h1>
<hr />
<p>Submission # @Model.SubmissionId <br />
    Title: @Model.SubmissionTitle</p>

<p>Instructions: Enter an stfm.org email address below.  The accepted email for the above submission will be
    sent to that address.Then review the email to ensure it looks correct for that submission and its conference.
    If it looks correct you can forward the email to the presenter who requested it.  <br />
    If it does not look correct you should notify STFM IT and they will handle getting the presenter
    a new copy of the accepted email.</p>

@if (ViewBag.error != null) 
{
    <h3 style="color:red;">@ViewBag.error</h3>
}

<form asp-action="GetAcceptedEmailSent" asp-controller="SubmissionStatus">

    <div class="form-group">
        <p>Enter an STFM email address: <input id="stfmEmail" name="stfmEmail" type="text" /></p>
       
    </div>

    <input type="hidden" id="submissionId" name="submissionId" value="@Model.SubmissionId" />

    <button type="submit" class="btn btn-primary">Get Accepted Email</button> &nbsp;&nbsp;&nbsp;
    <a class="btn btn-default" href="@Url.Action("Index", "Home")">Cancel</a>

</form>

ConferenceSubmission/Views/SubmissionStatus/GetAcceptedEmailSent.cshtml
@{
    ViewData["Title"] = "Get Accepted Email Sent";
}
<h1 class="text-primary">Accepted Email Sent</h1>
<a class="card-link" asp-controller="SubmissionAdmin" asp-action="Index"><i class="fas fa-plus-square" aria-hidden="true"></i> Submission Admin Home</a>

<hr />
<p>The accept email for the submission was sent to @ViewBag.emailAddress</p>

ConferenceSubmission/Views/SubmissionStatus/RenameDropboxFile.cshtml
@{
    ViewData["Title"] = "Dropbox File Renamed";
}
    <h1 class="text-primary">Drobox File Was Renamed</h1>

ConferenceSubmission/Views/SubmissionStatus/SendCPQIDisclosureReminder.cshtml
@{
    ViewData["Title"] = "CPQI Disclosure Reminder";
}
<h1 class="text-primary">Email sent to presenter</h1>

ConferenceSubmission/Views/SubmissionStatus/SendIncompleteReminder.cshtml
@{
    ViewData["Title"] = "Reminder Email For Incomplete Submission Sent to Submitter/Main Presenter";
}
<h1 class="text-primary">Reminder Email For Incomplete Submission Sent to Submitter/Main Presenter</h1>

ConferenceSubmission/Views/SubmissionStatus/UpdateSessionWithRoom.cshtml
@{
    ViewData["Title"] = "Session Updated With Room";
}
<h1 class="text-primary">Session Updated With Room</h1>

<p>Session Updated</p>

ConferenceSubmission/Views/SubmissionStatus/UpdateSubmissionStatusAndEmailPresenters.cshtml
@{
    ViewData["Title"] = "Submission Status Changed";
}
<h1 class="text-primary">Submission Status Changed</h1>

<p>Submission Updated</p>