ConferenceSubmission/ViewModels/ReviewersAssignedToSubmissionViewModel.cs
using System;
using System.Collections.Generic;
using ConferenceSubmission.Models;

namespace ConferenceSubmission.ViewModels
{
    public class ReviewersAssignedToSubmissionViewModel
    {

        public List<SubmissionReviewer> reviewers { get; set; }

        public Conference Conference { get; set; }

        public Submission Submission { get; set; }

        public ReviewersAssignedToSubmissionViewModel()
        {

            reviewers = new List<SubmissionReviewer>();

        }


    }
}

ConferenceSubmission/ViewModels/ReviewersStatusViewModel.cs
using System;
using ConferenceSubmission.Models;
using System.Collections.Generic;

namespace ConferenceSubmission.ViewModels
{
    public class ReviewersStatusViewModel
    {
        public ReviewersStatusViewModel()
        {
        }

        public string ConferenceLongName { get; set; }

        public int ConferenceId { get; set; }

        public List<ReviewerStatus> reviewerStatuses { get; set; }


    }
}

ConferenceSubmission/ViewModels/SubmissionCategoryReviewIndexViewModel.cs
using System;
using System.Collections.Generic;
using ConferenceSubmission.Models;
namespace ConferenceSubmission.ViewModels

{
    public class SubmissionCategoryReviewIndexViewModel
    {
        public List<SubmissionCategoryViewModel> submissionCategoryViewModels { get; set; }

        public Conference conference { get; set; }

        public SubmissionCategoryReviewIndexViewModel()
        {
            submissionCategoryViewModels = new List<SubmissionCategoryViewModel>();
        }
    }
}

ConferenceSubmission/ViewModels/SubmissionDetailedReview.cs
using ConferenceSubmission.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace ConferenceSubmission.ViewModels
{
    /// <summary>
    /// Models the detailed review data for
    /// a specific submission.
    /// </summary>
    public class SubmissionDetailedReview
    {

        public int SubmissionId { get; set; }

        public string SubmissionTitle { get; set; }

        public User MainPresenter { get; set; }

        public string SubmissionAbstract { get; set; }

        public Double AverageReviewScore { get; set; }

        public List<Review> SubmissionCompletedReviews { get; set; }

        public SubmissionDetailedReview()
        {

            SubmissionCompletedReviews = new List<Review>();
        }



    }
}

ConferenceSubmission/ViewModels/SubmissionReviewersNotDone.cs
using ConferenceSubmission.Models;
using System.Collections.Generic;

namespace ConferenceSubmission.ViewModels

{

    public class SubmissionReviewersNotDone
    {

        public List<SubmissionReviewer> submissionReviewersNotDone = new List<SubmissionReviewer>();

        public string ConferenceLongName { get; set; }

         public Submission Submission { get; set; }

        public SubmissionReviewersNotDone()
        {
        }

    }
}

ConferenceSubmission/ViewModels/SubmissionsNotReviewedViewModel.cs
using System;
using System.Collections.Generic;
using ConferenceSubmission.Models;

namespace ConferenceSubmission.ViewModels
{
    public class SubmissionsNotReviewedViewModel
    {
        public Conference Conference { get; set; }

        public List<Submission> SubmissionsNotAssignedToReviewer { get; set; }

        public List<Submission> SubmissionsNoReviewedCompleted { get; set; }

        public SubmissionsNotReviewedViewModel()
        {

            SubmissionsNotAssignedToReviewer = new List<Submission>();

            SubmissionsNoReviewedCompleted = new List<Submission>();

        }


    
    }
}

ConferenceSubmission/ViewModels/SubmissionsReviewStatusViewModel.cs
using System.Collections.Generic;

namespace ConferenceSubmission.ViewModels
{
    public class SubmissionsReviewStatusViewModel
    {

        public SubmissionsReviewStatusViewModel() { }

        public string ConferenceLongName { get; set; }

        public int ConferenceId { get; set; }

        public List<SubmissionReviewStatus> SubmissionsReviewStatus {get; set;}
    }
}

ConferenceSubmission/Controllers/ReviewAdminController.cs
using ConferenceSubmission.Mappers;
using ConferenceSubmission.Services;
using ConferenceSubmission.ViewModels;
using ConferenceSubmission.BindingModels;
using ConferenceSubmission.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Serilog;
using DinkToPdf;
using DinkToPdf.Contracts;
using System.IO;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Http;
using Azure.Storage.Blobs.Models;
using Azure.Storage.Blobs;
using ConferenceSubmission.Migrations;

namespace ConferenceSubmission.Controllers
{
    [Authorize("ConferenceAdmin")]
    public class ReviewAdminController : Controller
    {

        private readonly ISubmissionService _submissionService;
        private readonly IReviewerService _reviewerService;
        private readonly IReviewService _reviewService;
        private readonly IReviewAdminService _reviewAdminService;
        private readonly ISubmissionCategoryService _submissionCategoryService;
        private readonly IConverter _converter;
        private readonly ISubmissionPrintService _submissionPrintService;
        private readonly IConferenceService _conferenceService;
        private IConfiguration _configuration;

        public ReviewAdminController(IReviewerService reviewerService, 
                                     ISubmissionService submissionService,
                                     IReviewService reviewService,
                                     IReviewAdminService reviewAdminService,
                                     ISubmissionCategoryService submissionCategoryService,
                                     IConverter converter,
                                     ISubmissionPrintService submissionPrintService,
                                     IConferenceService conferenceService,
                                     IConfiguration configuraton
                                     )
        {
            _submissionService = submissionService;

            _reviewService = reviewService;

            _reviewerService = reviewerService;

            _reviewAdminService = reviewAdminService;

            _submissionCategoryService = submissionCategoryService;

            _converter = converter;

            _submissionPrintService = submissionPrintService;

            _conferenceService = conferenceService;

            _configuration = configuraton;

        }


        public ActionResult Index()
        {
            List<Conference> conferences =_conferenceService.GetConferencesWithUnstartedStatus();

            var model = new ReviewAdminHomePageViewModel()
            {
                conferences = conferences

            };

            return View(model);

        }

        public ActionResult SubmissionCategoryReviewIndex(int conferenceId)
        {

            List<SubmissionCategoryViewModel> categories = _submissionCategoryService.GetActiveSubmissionCategories(conferenceId);

            Conference conference = _conferenceService.GetConference(conferenceId);

            var model = new SubmissionCategoryReviewIndexViewModel()
            {
                submissionCategoryViewModels = categories,
                conference = conference

            };

            return View(model);


        }

        /// <summary>
        /// Responds to user's request to view the average review
        /// score for each submission in the provided category.
        /// </summary>
        /// <returns>View with submissions and their average review score</returns>
        /// <param name="categoryId">Category identifier.</param>
        public ActionResult SubmissionCategoryAverageReviewScores(int categoryId)
        {

            List<SubmissionsAverageReviewScore> submissionsAverageReviews = _reviewAdminService.GetCompletedReviewsForCategoryWithAverageReviewScore(categoryId);

            SubmissionCategory submissionCategory = _submissionCategoryService.GetSubmissionCategory(categoryId);

            var model = new SubmissionsAverageReviewScoreViewModel()
            {

                SubmissionsAverageReviews = submissionsAverageReviews,

                ConferenceLongName = submissionCategory.Conference.ConferenceLongName,

                SubmissionCategoryName = submissionCategory.SubmissionCategoryName,

                CategoryId = categoryId


            };

            return View(model);
        }


        public ActionResult UsersWithMoreThenTwoSubmissions(int conferenceId)
        {


            List<UserMultipleSubmissionsViewModel> userMultipleSubmissionsViewModels = _reviewAdminService.GetUsersWithMoreThenTwoSubmissions(conferenceId, 1);


            Conference conference = _conferenceService.GetConference(conferenceId);

            var model = new ConferenceUserMultipleSubmissionsViewModel
            {

                
                Conference = conference,

                UserMultipleSubmissionsViewModels = userMultipleSubmissionsViewModels


            };

            return View(model);

        }


        /// <summary>
        /// Responds to user request to get the detailed reviews of all
        /// submissions in the provided category.
        /// </summary>
        /// <returns>View page showing detailed reviews</returns>
        /// <param name="categoryId">Category identifier.</param>
        public ActionResult SubmissionCategoryDetailedReviews(int categoryId)
        {

            List<SubmissionDetailedReview> submissionDetailedReviews = _reviewAdminService.GetSubmissionDetailedReviews(categoryId);

            SubmissionCategory submissionCategory = _submissionCategoryService.GetSubmissionCategory(categoryId);


            var model = new SubmissionsDetailedReviewsViewModel()
            {

                ConferenceLongName = submissionCategory.Conference.ConferenceLongName,

                SubmissionCategoryName = submissionCategory.SubmissionCategoryName,

                SubmissionDetailedReviews = submissionDetailedReviews,

                SubmissionCategoryId = submissionCategory.SubmissionCategoryId



            };

            return View(model);

        }

        public ActionResult SubmissionDetailedReviews(int submissionId, int categoryId)
        {

            List<SubmissionDetailedReview> submissionDetailedReviews = _reviewAdminService.GetSubmissionDetailedReviewsForSubmission(submissionId);

            SubmissionCategory submissionCategory = _submissionCategoryService.GetSubmissionCategory(categoryId);


            var model = new SubmissionsDetailedReviewsViewModel()
            {

                ConferenceLongName = submissionCategory.Conference.ConferenceLongName,

                SubmissionCategoryName = submissionCategory.SubmissionCategoryName,

                SubmissionDetailedReviews = submissionDetailedReviews,

                SubmissionCategoryId = submissionCategory.SubmissionCategoryId



            };

            return View(model);

        }

        public ActionResult SubmissionDetailedReviewsNoCategory(int submissionId)
        {

            List<SubmissionDetailedReview> submissionDetailedReviews = _reviewAdminService.GetSubmissionDetailedReviewsForSubmission(submissionId);

            SubmissionCategory submissionCategory = _submissionCategoryService.GetSubmissionCategory(submissionDetailedReviews[0].SubmissionCompletedReviews[0].Submission.SubmissionCategoryId);


            var model = new SubmissionsDetailedReviewsViewModel()
            {

                ConferenceLongName = submissionCategory.Conference.ConferenceLongName,

                SubmissionCategoryName = submissionCategory.SubmissionCategoryName,

                SubmissionDetailedReviews = submissionDetailedReviews,

                SubmissionCategoryId = submissionCategory.SubmissionCategoryId



            };

            return View("SubmissionDetailedReviews", model);

        }

        public ActionResult ReviewersNotDone(int conferenceId)
        {

            List<ReviewIncomplete> reviewersNotDone = null;
            try
            {
               reviewersNotDone = _reviewAdminService.GetReviewersNotDone(conferenceId);

            } catch (Exception ex)
            {

                Log.Error("Unable to get reviewers not done: " + ex.Message);
            }

            var model = new ReviewIncompleteViewModel()
            {

                ConferenceLongName = _conferenceService.GetConference(conferenceId).ConferenceLongName,
                reviewIncomplete = reviewersNotDone

            };

            return View(model);

        }

        public ActionResult ReviewersStatus(int conferenceId)
        {

            List<ReviewerStatus> reviewers = null;

            try
            {

                reviewers = _reviewAdminService.GetReviewersStatus(conferenceId);

            } catch (Exception ex)
            {

                Log.Error("Unable to get reviewers status: " + ex.Message);
            }


            var model = new ReviewersStatusViewModel()
            {
                ConferenceLongName = _conferenceService.GetConference(conferenceId).ConferenceLongName,
                ConferenceId = conferenceId,
                reviewerStatuses = reviewers

            };

        return View(model);


        }

        public ActionResult SubmissionsReviewStatus(int conferenceId)
        {

            List<SubmissionReviewStatus> subissionsReviewStatus = _reviewAdminService.GetSubmissionsReviewStatus(conferenceId);

            var model = new SubmissionsReviewStatusViewModel()
            {
                ConferenceLongName = _conferenceService.GetConference(conferenceId).ConferenceLongName,
                ConferenceId = conferenceId,
                SubmissionsReviewStatus = subissionsReviewStatus
            };

            return View(model);


        }

ConferenceSubmission/Views/ReviewAdmin/AssignReviewers.cshtml
@model ConferenceSubmission.ViewModels.ReviewAdminHomePageViewModel
@{
    ViewData["Title"] = "Review Admin - Assign Reviewers";
}
<a href="/submissionadmin"><i class="fas fa-home mr-1"></i> Conference Admin Home</a>
<h1 class="text-primary mar-top-10">Review Admin</h1>
<hr />

<h3>Assign Reviewers To Submissions</h3>

<a class="card-link" asp-controller="ReviewAdmin" asp-action="Index"><i class="fas fa-plus-square" aria-hidden="true"></i> Review Admin Home</a>
<hr />


@if (ViewData.ContainsKey("Error"))
{
    <h3 style="color:red;font-weight:bold">@ViewData["Error"]</h3>
} 
@if (ViewData.ContainsKey("Success"))
{
    
    <h3 style="color:rgreen;font-weight:bold">@ViewData["Success"]</h3>
}



 <p>Use the form below to upload reviewer assignments file:</p>
    <ol>
        <li>File of type .csv - REQUIRED</li>
        
    </ol>

    <div class="row">

        <div class="col-md-6">

            <form method="post" enctype="multipart/form-data" asp-controller="ReviewAdmin" asp-action="UploadReviewerAssignments" onsubmit="return checkForm(this);">

                <div class="form-group">

                    <label> Select Reviewer Assignments File (Required)</label>

                    <input class="form-control" name="assignmentsFile" type="file" />

                </div>

               

                <div class="form-group">
                    
                    <input id="AddButton" name="AddButton" class="btn btn-success" type="submit" value="Submit File" />

                </div>

            </form>


        </div>

    </div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        function checkForm(form) // Submit button clicked
        {
            //
            // check form input values
            //

            form.AddButton.disabled = true;
            form.AddButton.value = "Please wait uploading...";
            return true;
        }</script>
}

ConferenceSubmission/Views/ReviewAdmin/Index.cshtml
@model ConferenceSubmission.ViewModels.ReviewAdminHomePageViewModel
@{
    ViewData["Title"] = "Review Admin";
}
<a href="/submissionadmin"><i class="fas fa-home mr-1"></i> Conference Admin Home</a>
<h1 class="text-primary mar-top-10">Review Admin</h1>
<hr />

<div class="card border-primary mb-3 mar-top-10">
    <div class="card-body">
        <div>
            <form asp-controller="ReviewAdmin" asp-action="ReviewersAssignedToSubmission" class="form-inline">
                <input placeholder="Submission Id" class="form-control form-control-sm" name="submissionId" id="submissionId" width="10" />
                <button class="btn-sm" type="submit">Find Reviewers</button>
            </form>
        </div>
        <span class="badge badge-primary pad-5 text-13 mar-top-3">
            <a class="card-link" asp-controller="ReviewAdmin" asp-action="ViewAllReviewers">All Reviewers</a>
        </span>
        <span class="badge badge-primary pad-5 mar-left-3 text-13 mar-top-3">
            <a class="card-link" asp-controller="ReviewAdmin" asp-action="FindPeopleByLastName" asp-route-lastName="jjjjjjjj">Add New Reviewer</a>
        </span>
        <span class="badge badge-primary pad-5 mar-left-3 text-13 mar-top-3">
            <a class="card-link" asp-controller="ReviewAdmin" asp-action="UploadReviewers">Upload New Reviewers</a>
        </span>
        <span class="badge badge-primary pad-5 mar-left-3 text-13 mar-top-3">
            <a class="card-link" asp-controller="ReviewAdmin" asp-action="UploadReviewerAssignments">Upload Reviewer Assignments</a>
        </span>
        <span class="badge badge-primary pad-5 mar-left-3 text-13">
            <a class="card-link" asp-controller="SubmissionAdmin" asp-action="FormPreview">Preview Forms</a>
        </span>
    </div>

</div>

<h2 class="color-primary">Conferences Undergoing Review</h2>
<hr />
@if (Model.conferences == null || Model.conferences.Count == 0)
{
    <p>There are no Conferences undergoing review at this time.</p>
}
@foreach (var conference in Model.conferences.OrderByDescending(c => c.ConferenceCFPEndDate))
{
    <div class="card border-primary mb-3">
        <div class="card-body">
            <h4 class="card-title">@Html.Raw(conference.ConferenceLongName)</h4>
            <p class="card-text"><strong>Review Deadline: </strong>@conference.ConferenceSubmissionReviewEndDate</p>

            <span class="badge badge-primary pad-5 text-13 mar-top-3">
                <a class="card-link" asp-controller="ReviewAdmin" asp-action="ReviewersStatus" asp-route-ConferenceId="@conference.ConferenceId">Reviewers Status</a>
            </span>
            <span class="badge badge-primary pad-5 mar-left-3 text-13 mar-top-3">
                <a class="card-link" asp-controller="ReviewAdmin" asp-action="SubmissionCategoryReviewIndex" asp-route-ConferenceId="@conference.ConferenceId">Submission Category Review Details</a>
            </span>
            <span class="badge badge-primary pad-5 mar-left-3 text-13 mar-top-3">
                <a class="card-link" asp-controller="ReviewAdmin" asp-action="UsersWithMoreThenTwoSubmissions" asp-route-ConferenceId="@conference.ConferenceId">People With More Than Two Submissions</a>
            </span>
            <span class="badge badge-primary pad-5 mar-left-3 text-13 mar-top-3">
                <a class="card-link" asp-controller="ReviewAdmin" asp-action="SubmissionsNotReviewed" asp-route-ConferenceId="@conference.ConferenceId">Submissions Not Reviewed</a>
            </span>
            <span class="badge badge-primary pad-5 mar-left-3 text-13 mar-top-3">
                <a class="card-link" asp-controller="ReviewAdmin" asp-action="SubmissionsReviewStatus" asp-route-ConferenceId="@conference.ConferenceId">Submissions Review Status</a>
            </span>
        </div>
    </div>
    <hr />
}

ConferenceSubmission/Views/ReviewAdmin/ReviewersAssignedToSubmission.cshtml
@model ConferenceSubmission.ViewModels.ReviewersAssignedToSubmissionViewModel
@using ConferenceSubmission.Extensions
@{
    ViewData["Title"] = "Review Admin - Reviewers Assigned To Submission";
}
    <div class="col-md-7 col-lg-8">
        <h3>Reviewers Assigned To Submission # @Model.Submission.SubmissionId - @Model.Submission.SubmissionTitle</h3>
        <a class="card-link" asp-controller="ReviewAdmin" asp-action="Index"><i class="fas fa-plus-square" aria-hidden="true"></i> Review Admin Home</a>
        <hr />
        <h4>
            <b>Conference: @Html.Raw(Model.Conference.ConferenceLongName)</b>

        </h4>

        @if (Model.reviewers.Count > 0)
        {

            <table class="display" id="reviewersAssignedToSubmission" style="width:100%;">
                <thead>
                    <tr>
                        <th data-priority="1">STFM User ID</th>
                        <th>Reviewer Name</th>
                        <th>Reviewer Email</th>
                        <th>Reviewer's Assignments</th>



                    </tr>
                </thead>

                @foreach (var submissionReviewer in Model.reviewers)
                {
                    <tr>
                        <td>@submissionReviewer.Reviewer.StfmUserId</td>
                        <td>@submissionReviewer.Reviewer.ReviewerName</td>
                        <td>@submissionReviewer.Reviewer.ReviewerEmail</td>
                        <td>
                            <a asp-controller="ReviewAdmin" asp-action="ViewReviewerAssignments"
                               asp-route-stfmUserId="@submissionReviewer.Reviewer.StfmUserId" asp-route-conferenceId="@Model.Conference.ConferenceId">Assignments</a>
                        </td>
                    </tr>

                }

            </table>

        } else
        {
            <p>There are no reviewers assigned to @Model.Submission.SubmissionId - @Model.Submission.SubmissionTitle.</p>
        }

        </div>
@{await Html.RenderPartialAsync("DataTableScripts", new DataTableScriptsOptions
    {
        IncludeDownloadAsCSVScripts = true
    });}

@{await Html.RenderPartialAsync("DataTableSetup", new DataTableParameters
    {
        ElementId = "reviewersAssignedToSubmission",
        DefaultPageLength = 25,
        LengthMenuValues = { 5, 10, 25, 50, -1 },
        LengthMenuDisplayValues = { "5", "10", "25", "50", "All" },
        DownloadAsCSV = true,
        SessionStateStorage = false
    });}

ConferenceSubmission/Views/ReviewAdmin/ReviewersStatus.cshtml
@model ConferenceSubmission.ViewModels.ReviewersStatusViewModel
@{
    ViewData["Title"] = "Review Admin - Reviewers Status";
}


<div>
    <h3>Reviewers Status</h3>
    <a class="card-link" asp-controller="ReviewAdmin" asp-action="Index"><i class="fas fa-plus-square" aria-hidden="true"></i> Review Admin Home</a>
    <hr />
    <h4>
        <b>Conference:</b> @Html.Raw(Model.ConferenceLongName) </b>

    </h4>

    @if (Model.reviewerStatuses.Count > 0)
    {
        <table class="display" id="reviewersStatusTable" style="width:100%;">
            <thead>
                <tr>
                    <th data-priority="1">Reviewer</th>
                    <th data-priority="2">Email</th>
                    <th data-priority="4">Reviews Assigned</th>
                    <th data-priority="3">Reviews Completed</th>
                    <th date-priority="5">Reviews Not Completed</th>
                </tr>
            </thead>

            @foreach (var reviewerStatus in Model.reviewerStatuses)
            {
                <tr>
                    <td>
                        <a class="card-link" asp-controller="ReviewAdmin" asp-action="ViewReviewerAssignments"
                        asp-route-stfmUserId="@reviewerStatus.Reviewer.STFMUserId" asp-route-conferenceId="@Model.ConferenceId">@reviewerStatus.Reviewer.GetFullNamePretty()</a>
                    </td>
                    <td>@reviewerStatus.Reviewer.Email</td>
                    <td>@reviewerStatus.NumberOfReviewsAssigned</td>
                    <td>@reviewerStatus.NumberOfReviewsCompleted</td>
                    <td>@(reviewerStatus.NumberOfReviewsAssigned - reviewerStatus.NumberOfReviewsCompleted)</td>
                </tr>

            }

        </table>
    }
    else
    {
        <p>There are no reviewer asssignments.</p>
    }
</div>
@{await Html.RenderPartialAsync("DataTableScripts", new DataTableScriptsOptions
    {
        IncludeDownloadAsCSVScripts = true
    });}

@{await Html.RenderPartialAsync("DataTableSetup", new DataTableParameters
    {
        ElementId = "reviewersStatusTable",
        DefaultPageLength = 25,
        LengthMenuValues = { 5, 10, 25, 50, -1 },
        LengthMenuDisplayValues = { "5", "10", "25", "50", "All" },
        DownloadAsCSV = true,
        SessionStateStorage = false
    });}

ConferenceSubmission/Views/ReviewAdmin/SubmissionCategoryAverageReviewScores.cshtml
@model ConferenceSubmission.ViewModels.SubmissionsAverageReviewScoreViewModel
@{
    ViewData["Title"] = "Review Admin - Submissions With Average Review Score";
}


<div>
    <h3>Submissions With Average Review Score</h3>
    <a class="card-link" asp-controller="ReviewAdmin" asp-action="Index"><i class="fas fa-plus-square" aria-hidden="true"></i> Review Admin Home</a>
    <hr />
    <h4>
        <b>Conference:</b> @Html.Raw(Model.ConferenceLongName) <br />
        <b>Category:</b> @Model.SubmissionCategoryName
    </h4>

    @if (Model.SubmissionsAverageReviews.Count > 0)
    {
        <table class="display" id="submissionsReviewedTable" style="width:100%;">
            <thead>
                <tr>
                    <th data-priority="1">Submission Id</th>
                    <th data-priority="2">Submission Status</th>
                    <th data-priority="3">Submission Title</th>
                    <th data-priority="4">Submission Category</th>
                    <th data-priority="5">Average Review Score</th>
                    <th data-priority="6">Behavioral Science Credit</th>
                    <th data-priority="6">KeyWord One</th>
                    <th data-priority="7">KeyWord Two</th>
                    <th data-priority="8">Multi-Institutional</th>
                    <th data-priority="9">Learner Included</th>
                    <th data-priority="10">Academic Coordinator</th>
                    <th data-priority="11">Submitter</th>
                    <th data-priority="11">Submitter Email</th>
                    <th data-priority="12">Lead Presenter</th>
                    <th data-priority="12">Lead Presenter Email</th>
                    <th>Detailed Review</th>
                </tr>
            </thead>

            @foreach (var submissionAverageReview in Model.SubmissionsAverageReviews)
            {
                <tr>
                    <td>@submissionAverageReview.SubmissionId</td>
                    <td>@submissionAverageReview.SubmissionStatus</td>
                    <td>@submissionAverageReview.SubmissionTitle</td>
                    <td>@submissionAverageReview.SubmissionCategory</td>
                    <td>@submissionAverageReview.AverageReviewScore</td>
                    <td>@submissionAverageReview.BehavioralScience</td>
                    <td>@submissionAverageReview.KeyWordOne</td>
                    <td>@submissionAverageReview.KeyWordTwo</td>
                    <td>@submissionAverageReview.MultiInstitutional</td>
                    <td>@submissionAverageReview.StudentIncluded</td>
                    <td>@submissionAverageReview.AcademicCoordinator</td>
                    <td>@submissionAverageReview.SubmitterUser.GetFullNamePretty()</td>
                    <td>@submissionAverageReview.SubmitterUser.Email</td>
                    <td>
                        @if (submissionAverageReview.LeadPresenterUser != null)
                        {
                            @submissionAverageReview.LeadPresenterUser.GetFullNamePretty()
                        }
                    </td>
                    <td>
                        @if (submissionAverageReview.LeadPresenterUser != null)
                        {
                            @submissionAverageReview.LeadPresenterUser.Email
                        }
                    </td>


                    <td> <a class="card-link" asp-controller="ReviewAdmin" asp-action="SubmissionDetailedReviews" asp-route-categoryId="@Model.CategoryId" asp-route-submissionId="@submissionAverageReview.SubmissionId"><i class="fas fa-plus-square" aria-hidden="true"></i> Detailed Reviews</a></td>

                </tr>

            }

        </table>
    }
    else
    {
        <p>There are no completed reviews in this category.</p>
    }
</div>
@{
    await Html.RenderPartialAsync("DataTableScripts", new DataTableScriptsOptions
            {
                IncludeDownloadAsCSVScripts = true
            });
}

@{
    await Html.RenderPartialAsync("DataTableSetup", new DataTableParameters
            {
                ElementId = "submissionsReviewedTable",
                DefaultPageLength = 25,
                LengthMenuValues = { 5, 10, 25, 50, -1 },
                LengthMenuDisplayValues = { "5", "10", "25", "50", "All" },
                DownloadAsCSV = true,
                SessionStateStorage = false
            });
}